jobs:
  provenance:
    needs: [build]
    uses: slsa-framework/slsa-github-builder/.github/workflows/generator_generic_slsa3.yml@v1.5.0
    permissions:
      actions: read
      id-token: write
      contents: write
    with:
      subject-base64: ${{ steps.build.outputs.hashes }}
      upload-assets: true