jobs:
 publish:
   needs: ["build", "provenance"]
   permissions:
     contents: write
   runs-on: "ubuntu-latest"
   steps:
     # Download the built distributions
     - uses: "actions/download-artifact@..."
       with:
         name: "dist"
         path: "dist/"
    
     # Upload distributions to the GitHub Release
     - env:
         GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
       run: |
         gh release upload ${{ github.ref_name }} \
           dist/* --repo ${{ github.repository }}
    
     # Publish distributions to PyPI
     - uses: "pypa/gh-action-pypi-publish@..."
       with:
         user: __token__
         password: ${{ secrets.PYPI_TOKEN }}
